on:
  push:
    branches:
      - main
jobs:
  example:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - run: npx 'github:dtinth/publish-storyboard#main' --input=fixture
